apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  creationTimestamp: null
  name: {{ .Values.backend.name }}
spec:
  maxReplicas: {{ .Values.backend.backendhpamaxreplica }}
  minReplicas: {{ .Values.backend.backendhpaminreplica }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.backend.name }}
  targetCPUUtilizationPercentage: 80
status:
  currentReplicas: 0
  desiredReplicas: 0
