apiVersion: v1
kind: PersistentVolume
metadata:
  name: backend-pv
spec:
  capacity:
    storage: {{ .Values.backend.backendPvStorageCapacity }}  
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain  
  hostPath:
    path: "/mnt/data"  # Adjust the path based on your setup, if on local machine then you have to create a mount path 
