apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.backend.pvClaim }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.backend.backendPVCStoragerequest }}  # Must match or be less than the PV size
