apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: NodePort
  selector:
    app: {{ .Values.frontend.label }}
  ports:
    - port: {{ .Values.frontend.frontendServicePort}}
      targetPort: {{ .Values.frontend.frontendContainerport}}
      nodePort: {{ .Values.frontend.frontendNodePort}}
