apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: abdulmusavvirrohe/3-tier-application-backend:1.0
        ports:
        - containerPort: 7000
          name: app-svc-port
        envFrom:
        - secretRef:
            name: backend-secret
